# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "jupyterVM"

  # Misma IP del profe
  config.vm.network :private_network, ip: "192.168.90.3"
config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true

  # Recursos opcionales
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2
  end

  # Provisioner Shell
  config.vm.provision "shell", path: "jupyter.sh"
end
